version: '3.8'

services:
  iris_ml_app:
    build: .
    container_name: iris_ml_app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_tracking_server:5000
    volumes:
      - ./mlruns:/app/mlruns
    depends_on:
      - mlflow_tracking_server

  mlflow_tracking_server:
    image: mlflow/mlflow
    container_name: mlflow_tracking_server
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - ./mlruns:/mlflow/mlruns
    ports:
      - "5000:5000"
